[tool.poetry]
name = "pyprocrustes"
version = "0.1.0"
description = ""
authors = ["Manuel YGUEL <yguel@unistra.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
